version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "9797:80"
    volumes:
      - /mnt/c/dev/logs/fluentd/:/usr/share/nginx/html/
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        
        tag: maiks.nginx.container

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.9.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"